branch-defaults:
  master:
    environment: school-points
    group_suffix: null
global:
  application_name: app-school-points
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker 18.06.1-ce
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
